import { defineAIDataFields } from "@gridframe/server";

const aiDataFields = defineAIDataFields([
  {
    key: "revenue",
    label: "Revenue",
    description: "Recognised order revenue in the account currency.",
    type: "number",
    role: "metric",
    allowedAggregations: ["sum", "average", "min", "max"],
    filterable: true,
    sortable: true,
  },
  {
    key: "order_id",
    label: "Order ID",
    type: "string",
    role: "dimension",
    allowedAggregations: ["count"],
    filterable: true,
    sortable: true,
  },
  {
    key: "order_value",
    label: "Order value",
    type: "number",
    role: "metric",
    allowedAggregations: ["sum", "average", "min", "max"],
    filterable: true,
    sortable: true,
  },
  {
    key: "refund_rate",
    label: "Refund rate",
    type: "number",
    role: "metric",
    allowedAggregations: ["average", "min", "max"],
    filterable: true,
    sortable: true,
  },
  {
    key: "order_status",
    label: "Order status",
    type: "category",
    role: "dimension",
    filterable: true,
    sortable: true,
  },
  {
    key: "product",
    label: "Product",
    type: "category",
    role: "dimension",
    filterable: true,
    sortable: true,
  },
  {
    key: "region",
    label: "Region",
    type: "category",
    role: "dimension",
    filterable: true,
    sortable: true,
  },
  {
    key: "channel",
    label: "Sales channel",
    type: "category",
    role: "dimension",
    filterable: true,
    sortable: true,
  },
  {
    key: "created_at",
    label: "Created at",
    description: "The time an order was created.",
    type: "datetime",
    role: "time",
    filterable: true,
    sortable: true,
  },
  {
    key: "customer_email",
    label: "Customer email",
    type: "string",
    role: "dimension",
    filterable: false,
    sortable: false,
    sensitive: true,
  },
]);

export { aiDataFields };
